### ISSUE TITLE
Keeping track of optional installs makes it hard to go back to a standard setup.

### ISSUE THREAD

**Issue by skohlbr** [tu-darmstadt-ros-pkg/workspace_scripts#1]
While keeping track of optional installs make sense for some use cases, the use case "revert the whole workspace to a standard setup on `update`" is broken with that approach, as what the `update` now depends on what optional installs have been installed before. For instance, for testing the whole body planner, quite a few standard repos (moveit, robot models etc.) had to be switched to non-default branches. We should support the "revert to standard setup after test" use case directly, as it is one very frequently encountered.

**Comment by astumpf** [comment]
That depends on how you define the "standard workspace". The install infrastructure is implemented with the idea that the default install does only provide the basic minimalistic setup and you complete your workspace by additional features provided by those optional installs. Thus, default + optional is indeed the "standard workspace setup" by this paradigm.
This paradigm assumes you manage your workspace installs in a modular (feature-based) fashion such as done with our THORMANG or TurtleBot workspaces, so users (developers) must only install and compile parts of the robot setup which are relevant for their work.
In your example, you must only `uninstall` the whole body planner. This will indeed not remove the additionally cloned repositories (missing feature) but prevent that the branches are switched by this optional install. So long as the "default" branch was set by another (or even default) install file that will be used instead now. So you can simply turn on/off specific setups by installing/uninstalling the desired optionals.
