### ISSUE TITLE
Do not force sudo calls as default option for update script

### ISSUE THREAD

**Issue by astumpf** [tu-darmstadt-ros-pkg/workspace_scripts#3]
As sudo is a privileged command, it should not be assumed as the default option and can even be dangerous. Instead, calling the non-sudo variant should be the default behavior and sudo calls should be specified with an argument.

Now, typing admin password as default option or be forced to use --no-sudo is very tedious.

See:
https://github.com/tu-darmstadt-ros-pkg/workspace_scripts/commit/59a8482ecf89b2a19b67f9fec9674aedce1b69b9#commitcomment-42633572
https://github.com/tu-darmstadt-ros-pkg/workspace_scripts/commit/e9c3c518fe5cdf06e808857b00706aa4cb48a8ed#commitcomment-42633546

**Comment by StefanFabian** [comment]
As discussed the update command was reworked and the system package update was moved to an overlay.
See b7b6ff14dc55bb918459c6fde4f829d03ebf286f
